name: CI

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          

  updatebranches:
    name: Merge Pull Request
    runs-on: [ubuntu-latest]
    needs: [build]
    if: github.event.pull_request.merged == true
    steps:
      - name: Raise PR
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "homol"
          base: main
          title: "Auto update Homol <- Main"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}''>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}''>
          body:
            Automatic PR creation
          token: ${{ secrets.ACTION_SECRET }}
          delete-branch: false

      - name: Approve PR
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.ACTION_SECRET }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}

      - name: Merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.ACTION_SECRET }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}
          method: squash
