name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  automerge:
    name: Merge Pull Request
    uses: actions/github-script@latest
    with:
      scripts: |
        github.pullRequests.merge ({
          owner: context.payload.repository.owner.login,
          repo: context.payload.repositoty.name,
          pull_number: context.payload.pull_request.number
        })
        
        github-token: ${{github.token}}
    
